feature/Exercicio-9
samuelcamilodacosta/node-api-boilerplate pull request #1
Opened 2021-11-23 03:33 UTC by samuelcamilodacosta

2021-11-23 18:58 UTC, samuelcamilodacosta commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sprint 03 - Exercício 9](https://trello.com/c/2jyJUJW7/307-sprint-03-exerc%C3%ADcio-9)

2021-11-23 21:13 UTC, felipe-nascimento-helpper commented
Teste

2021-11-23 21:17 UTC, felipe-nascimento-helpper requested changes

2021-11-23 21:17 UTC, felipe-nascimento-helpper commented on src/library/BaseValidator.ts
> +        },
O BaseValidator é para todas as entidades do projeto, inclua esses campos no ClientValidator

2021-11-23 21:17 UTC, felipe-nascimento-helpper commented on src/library/database/entity/Client.ts
> +    @BeforeInsert()
No mysql não precisa das triggers vc pode usar decorator que realizam isso automaticamente, como o CreateDateColumn

2021-11-23 21:17 UTC, felipe-nascimento-helpper commented on src/library/database/entity/Client.ts
> +    public id: ObjectID;
Banco de dados é Mysql, não tem ObjectID

2021-11-23 21:17 UTC, felipe-nascimento-helpper commented on src/library/database/repository/ClientRepository.ts
> +     * @param client - Dados do cliente
Documentação incorreta, @param {  DeepPartial<Client> } client - Dados.....

2021-11-23 21:17 UTC, felipe-nascimento-helpper commented on src/modules/users/v1/controllers/ClientController.ts
>          const { id } = req.params;
não precisa criar uma constante para pegar o id, como vc só irá usar uma vez no código passa req.params.id por parâmetro, lembre-se que variável é um espaço alocado em memória do nosso servidor...

2021-11-23 21:17 UTC, felipe-nascimento-helpper commented on src/modules/users/v1/middlewares/ClientValidator.ts
> +        name: BaseValidator.validators.name,
Tira do Base e inclui aqui, assim por diante

2021-11-23 21:17 UTC, felipe-nascimento-helpper commented on src/modules/users/v1/middlewares/ClientValidator.ts
> +        duplicate: {
duplicate é um atributo de Cliente?

2021-11-23 21:17 UTC, felipe-nascimento-helpper commented on src/modules/users/v1/middlewares/ClientValidator.ts
> +                    if (req.body.name) {
inclua esta validação no name

2021-11-23 21:17 UTC, felipe-nascimento-helpper commented on src/modules/users/v1/middlewares/ClientValidator.ts
> +                    if (req.body.email) {
inclua esta validação no email

2021-11-23 21:17 UTC, felipe-nascimento-helpper commented on src/modules/users/v1/middlewares/ClientValidator.ts
> +            name: ClientValidator.model.name,
...ClientValidator.model, sempre deixe seu código legível

2021-11-23 21:17 UTC, felipe-nascimento-helpper commented on src/server.ts
>  const app: App = new App({
teste

2021-11-24 02:50 UTC, samuelcamilodacosta commented on src/modules/users/v1/middlewares/ClientValidator.ts
> +        duplicate: {
É uma propriedade para retornar erro no caso um atributo que seja único esteja duplicado no banco de dados, evitando no caso, gerar IDs que seriam inutilizados por não poderem ser cadastrados corretamente no BD. Estou reaproveitando o código dado no exemplo, como eu não dei um commit antes de mudar o nome de UserValidator para ClientValidator, não ficou muito claro.

2021-11-24 02:54 UTC, samuelcamilodacosta commented on src/modules/users/v1/middlewares/ClientValidator.ts
> +                    if (req.body.name) {
Refatorando o código agora, notei que não faz muito sentido eu manter name como unique já que posso ter vários clientes de mesmo nome.

2021-11-24 03:06 UTC, samuelcamilodacosta commented on src/modules/users/v1/middlewares/ClientValidator.ts
> +                    if (req.body.email) {
Eu posso jogar essa declaração de validação para Base Validator e iniciar ela na hora da adição, mas pelo código modelo que nos enviaram, acho que queriam que apresentasse os erros de duplicação dessa maneira, amanhã converso contigo para ver certinho sobre isso.

2021-11-24 04:14 UTC, samuelcamilodacosta commented on src/modules/users/v1/middlewares/ClientValidator.ts
> +            name: ClientValidator.model.name,
código adaptado para utilizar o spread.

2021-11-24 19:52 UTC, samuelcamilodacosta commented on src/library/database/entity/Client.ts
> +    @BeforeInsert()
Hmm, eu alterei, não achei muita documentação exemplificando o uso do CreateDateColumn, verifica se ficou correto, por favor.

2021-11-24 20:06 UTC, samuelcamilodacosta commented
-> Verificar se ficou correto as alterações solicitadas.

2021-11-26 20:59 UTC, felipe-nascimento-helpper requested changes

2021-11-26 20:59 UTC, felipe-nascimento-helpper commented on src/library/BaseValidator.ts
> +        email: {
Email, phone e status devem ser validators lá da classe Client. O baseValidator são validações comuns entre todos os módulos do sistema.

2021-12-01 15:34 UTC, samuelcamilodacosta commented
Aguardando verificação das alterações.

2021-12-04 00:38 UTC, closed without merging